### ISSUE TITLE
Artima Supersafe plugin installation instructions incorrect

### ISSUE THREAD

**Issue by colindean** [scalatest/scalatest-website#58]
On http://www.scalatest.org/install, after adding the Artima resolver, adding

```scala
addSbtPlugin("com.artima.supersafe" % "sbtplugin" % "1.1.0")
```

to `project/plugins.sbt` causes sbt to say that it can't find that plugin. Going to http://repo.artima.com/releases manually and poking around, I don't see it. That is, unless it's been simply renamed `supersafe`, in which case it's definitely there and the site needs updated to reflect the rename.

**Comment by cheeseng** [comment]
hi @colindean, the sbtplugin itself should resolve to this: 

http://repo.artima.com/releases/com/artima/supersafe/sbtplugin_2.10_0.13/1.1.0/

However, if you're using scala 2.12.0 to build your project, you should use version 1.1.1 instead, also I'll update the instructions to use the just released 1.1.1.

Thanks for reporting!  :)

**Comment by cheeseng** [comment]
Submitted a PR here: 

https://github.com/scalatest/scalatest-website/pull/59

**Comment by bvenners** [comment]
We have fixed the website now. Instructions should be correct.

**Comment by xnorme** [comment]
Same issue again with Scala 2.12.8. Plugin version needs to be update to "1.1.7"

**Comment by xnorme** [comment]
For scala 2.18, sbt 1.2 I had to add *both* of the following lines to `project/plugins.sbt` to make it work:
```
resolvers += "Artima Maven Repository" at "http://repo.artima.com/releases"
addSbtPlugin("com.artima.supersafe" % "sbtplugin" % "1.1.7")
```

**Comment by mskonovalov** [comment]
For scala `2.12`, sbt `1.3.4`
```
[error]   not found: not found: https://repo.artima.com/releases/com/artima/supersafe/supersafe_2.12/1.1.8/supersafe_2.12-1.1.8.pom
```
seems the problem is that auto scala version in plugin.sbt is `2.12` while the artifact is uploaded for `2.12.0` 
If I specify explicitly `scalaVersion := "2.12.0"` it is still the same
